Updated default bashrc profile

diff --git a/roles/base/files/bashrc b/roles/base/files/bashrc
--- a/roles/base/files/bashrc
+++ b/roles/base/files/bashrc
@@ -12,13 +12,25 @@ export LANG=en_US.UTF-8
 export LC_ALL=en_US.UTF-8
 export LC_CTYPE=en_US.UTF-8
 
+# Git Export
+if rpm -q git >/dev/null 2>&1
+    then
+        if [[ -f ~/.ssh/ctc_ed25519 ]]
+            then
+                export GIT_SSH_COMMAND="ssh -i ~/.ssh/ctc_ed25519"
+        fi
+fi
+
 # User Aliases
 alias ll="ls -alh --color=auto"
 alias ls="ls -alh --color=auto"
 alias grep="grep --color=auto"
 
-# Git Export
-if rpm -q git
+# Change to the working directory
+if rpm -q ansible >/dev/null 2>&1
     then
-        export GIT_SSH_COMMAND="ssh -i ~/.ssh/ctc_ed25519"
+        if [[ -d ~/.ansible ]]
+            then
+                cd ~/.ansible || echo 'Could not change to ANSIBLE working directory'
+        fi
 fi
